-- CreateTable
CREATE TABLE "Testimonial" (
    "ID" TEXT NOT NULL,
    "RATING" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "TITLE" TEXT,
    "DESCRIPTION" TEXT,
    "PRODUCT_ID" TEXT,
    "USER_ID" TEXT,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("ID")
);

-- AddForeignKey
ALTER TABLE "Testimonial" ADD FOREIGN KEY ("PRODUCT_ID") REFERENCES "Product"("ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Testimonial" ADD FOREIGN KEY ("USER_ID") REFERENCES "User"("ID") ON DELETE SET NULL ON UPDATE CASCADE;
