-- CreateTable
CREATE TABLE "Category" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("ID")
);
