-- CreateTable
CREATE TABLE "User" (
    "ID" TEXT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "FIRST_NAME" TEXT NOT NULL,
    "LAST_NAME" TEXT NOT NULL,
    "DT_BIRTH" TIMESTAMP(3) NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "UserRole" (
    "ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,
    "ROLE_ID" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "Role" (
    "ID" TEXT NOT NULL,
    "NAME" TEXT NOT NULL,
    "CREATED_AT" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UPDATED_AT" TIMESTAMP(3) NOT NULL,

    PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "User.EMAIL_unique" ON "User"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "Role.NAME_unique" ON "Role"("NAME");

-- AddForeignKey
ALTER TABLE "UserRole" ADD FOREIGN KEY ("USER_ID") REFERENCES "User"("ID") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserRole" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "Role"("ID") ON DELETE CASCADE ON UPDATE CASCADE;
